### ISSUE TITLE
Could not execute entrypoint stage 'main' due to errors, provided by 'adventure-platform-fabric'!

### ISSUE THREAD

**Issue by RealKomander** [GeyserMC/Floodgate#462]
Floodgate doesn't work on fabric 1.20.2. Weird error, but it's confirmed to be caused by floodgate

```
[19:39:18] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'adventure-platform-fabric'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:387) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:385) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.24.jar:?]
        at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.24.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.24.jar:?]
        Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.fabricmc.fabric.impl.networking.server.ServerNetworkingImpl
                at net.fabricmc.fabric.api.networking.v1.ServerConfigurationNetworking.registerGlobalReceiver(ServerConfigurationNetworking.java:71) ~[fabric-networking-api-v1-3.0.10+b1792f7da0-7978eacecef623d6.jar:?]
                at net.fabricmc.fabric.impl.networking.CommonPacketsImpl.init(CommonPacketsImpl.java:36) ~[fabric-networking-api-v1-3.0.10+b1792f7da0-7978eacecef623d6.jar:?]
                at java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:198) ~[?:?]
                at com.sun.proxy.jdk.proxy3.$Proxy33.onInitialize(Unknown Source) ~[?:?]
                at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.24.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.24.jar:?]
                at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
                at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.24.jar:?]
                at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.24.jar:?]
        Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/class_2889.<init>(Lnet/minecraft/class_2540;)V @10: invokespecial
  Reason:
    Type uninitializedThis (current frame, stack[3]) is not assignable to 'net/minecraft/class_2889'
  Current Frame:
    bci: @10
    flags: { flagThisUninit }
    locals: { uninitializedThis, 'net/minecraft/class_2540' }
    stack: { uninitializedThis, integer, 'net/minecraft/class_2540', uninitializedThis, integer }
  Bytecode:
    0000000: 2a2b b600 332b 2a11 00ff b700 37b6 003b
    0000010: 2bb6 003e 2bb6 0033 b800 44b7 0046 b1
 [in thread "main"]
                at net.minecraft.class_2539.<clinit>(class_2539.java:217) ~[server-intermediary.jar:?]
                at net.fabricmc.fabric.impl.networking.server.ServerNetworkingImpl.<clinit>(ServerNetworkingImpl.java:41) ~[fabric-networking-api-v1-3.0.10+b1792f7da0-7978eacecef623d6.jar:?]
                at net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking.registerGlobalReceiver(ServerPlayNetworking.java:86) ~[fabric-networking-api-v1-3.0.10+b1792f7da0-7978eacecef623d6.jar:?]
                at net.kyori.adventure.platform.fabric.impl.ServerboundRegisteredArgumentTypesPacket.register(ServerboundRegisteredArgumentTypesPacket.java:47) ~[adventure-platform-fabric-5.10.0-144eb7082e02c5d6.jar:?]
                at net.kyori.adventure.platform.fabric.impl.AdventureCommon.setupCustomArgumentTypes(AdventureCommon.java:231) ~[adventure-platform-fabric-5.10.0-144eb7082e02c5d6.jar:?]
                at net.kyori.adventure.platform.fabric.impl.AdventureCommon.onInitialize(AdventureCommon.java:182) ~[adventure-platform-fabric-5.10.0-144eb7082e02c5d6.jar:?]
                ... 7 more
        Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.fabricmc.fabric.impl.networking.server.ServerNetworkingImpl
                at net.fabricmc.fabric.api.networking.v1.ServerConfigurationNetworking.registerGlobalReceiver(ServerConfigurationNetworking.java:71) ~[fabric-networking-api-v1-3.0.10+b1792f7da0-7978eacecef623d6.jar:?]
                at net.fabricmc.fabric.impl.recipe.ingredient.CustomIngredientSync.onInitialize(CustomIngredientSync.java:94) ~[fabric-recipe-api-v1-2.0.7+b1792f7da0-41a899f751408233.jar:?]
                at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.24.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.24.jar:?]
                at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
                at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.24.jar:?]
                at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.24.jar:?]
        Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/class_2889.<init>(Lnet/minecraft/class_2540;)V @10: invokespecial
  Reason:
    Type uninitializedThis (current frame, stack[3]) is not assignable to 'net/minecraft/class_2889'
  Current Frame:
    bci: @10
    flags: { flagThisUninit }
    locals: { uninitializedThis, 'net/minecraft/class_2540' }
    stack: { uninitializedThis, integer, 'net/minecraft/class_2540', uninitializedThis, integer }
  Bytecode:
    0000000: 2a2b b600 332b 2a11 00ff b700 37b6 003b
    0000010: 2bb6 003e 2bb6 0033 b800 44b7 0046 b1
 [in thread "main"]
                at net.minecraft.class_2539.<clinit>(class_2539.java:217) ~[server-intermediary.jar:?]
                at net.fabricmc.fabric.impl.networking.server.ServerNetworkingImpl.<clinit>(ServerNetworkingImpl.java:41) ~[fabric-networking-api-v1-3.0.10+b1792f7da0-7978eacecef623d6.jar:?]
                at net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking.registerGlobalReceiver(ServerPlayNetworking.java:86) ~[fabric-networking-api-v1-3.0.10+b1792f7da0-7978eacecef623d6.jar:?]
                at net.kyori.adventure.platform.fabric.impl.ServerboundRegisteredArgumentTypesPacket.register(ServerboundRegisteredArgumentTypesPacket.java:47) ~[adventure-platform-fabric-5.10.0-144eb7082e02c5d6.jar:?]
                at net.kyori.adventure.platform.fabric.impl.AdventureCommon.setupCustomArgumentTypes(AdventureCommon.java:231) ~[adventure-platform-fabric-5.10.0-144eb7082e02c5d6.jar:?]
                at net.kyori.adventure.platform.fabric.impl.AdventureCommon.onInitialize(AdventureCommon.java:182) ~[adventure-platform-fabric-5.10.0-144eb7082e02c5d6.jar:?]
                ... 7 more
        Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.fabricmc.fabric.impl.networking.server.ServerNetworkingImpl
                at net.fabricmc.fabric.api.networking.v1.ServerConfigurationNetworking.registerGlobalReceiver(ServerConfigurationNetworking.java:71) ~[fabric-networking-api-v1-3.0.10+b1792f7da0-7978eacecef623d6.jar:?]
                at net.fabricmc.fabric.impl.registry.sync.FabricRegistryInit.onInitialize(FabricRegistryInit.java:34) ~[fabric-registry-sync-v0-4.0.5+b1792f7da0-d4b7af4fa27bb654.jar:?]
                at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.24.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.24.jar:?]
                at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
                at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.24.jar:?]
                at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.24.jar:?]
        Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/class_2889.<init>(Lnet/minecraft/class_2540;)V @10: invokespecial
  Reason:
    Type uninitializedThis (current frame, stack[3]) is not assignable to 'net/minecraft/class_2889'
  Current Frame:
    bci: @10
    flags: { flagThisUninit }
    locals: { uninitializedThis, 'net/minecraft/class_2540' }
    stack: { uninitializedThis, integer, 'net/minecraft/class_2540', uninitializedThis, integer }
  Bytecode:
    0000000: 2a2b b600 332b 2a11 00ff b700 37b6 003b
    0000010: 2bb6 003e 2bb6 0033 b800 44b7 0046 b1
 [in thread "main"]
                at net.minecraft.class_2539.<clinit>(class_2539.java:217) ~[server-intermediary.jar:?]
                at net.fabricmc.fabric.impl.networking.server.ServerNetworkingImpl.<clinit>(ServerNetworkingImpl.java:41) ~[fabric-networking-api-v1-3.0.10+b1792f7da0-7978eacecef623d6.jar:?]
                at net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking.registerGlobalReceiver(ServerPlayNetworking.java:86) ~[fabric-networking-api-v1-3.0.10+b1792f7da0-7978eacecef623d6.jar:?]
                at net.kyori.adventure.platform.fabric.impl.ServerboundRegisteredArgumentTypesPacket.register(ServerboundRegisteredArgumentTypesPacket.java:47) ~[adventure-platform-fabric-5.10.0-144eb7082e02c5d6.jar:?]
                at net.kyori.adventure.platform.fabric.impl.AdventureCommon.setupCustomArgumentTypes(AdventureCommon.java:231) ~[adventure-platform-fabric-5.10.0-144eb7082e02c5d6.jar:?]
                at net.kyori.adventure.platform.fabric.impl.AdventureCommon.onInitialize(AdventureCommon.java:182) ~[adventure-platform-fabric-5.10.0-144eb7082e02c5d6.jar:?]
                ... 7 more
        Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.class_2539
                at com.ishland.vmp.VMPMod.onInitialize(VMPMod.java:21) ~[vmp-fabric-mc1.20.2-0.2.0+beta.7.120-all.jar:?]
                at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.24.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.14.24.jar:?]
                at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
                at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.14.24.jar:?]
                at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.24.jar:?]
                at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.24.jar:?]
                at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.24.jar:?]
        Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/class_2889.<init>(Lnet/minecraft/class_2540;)V @10: invokespecial
  Reason:
    Type uninitializedThis (current frame, stack[3]) is not assignable to 'net/minecraft/class_2889'
  Current Frame:
    bci: @10
    flags: { flagThisUninit }
    locals: { uninitializedThis, 'net/minecraft/class_2540' }
    stack: { uninitializedThis, integer, 'net/minecraft/class_2540', uninitializedThis, integer }
  Bytecode:
    0000000: 2a2b b600 332b 2a11 00ff b700 37b6 003b
    0000010: 2bb6 003e 2bb6 0033 b800 44b7 0046 b1
 [in thread "main"]
                at net.minecraft.class_2539.<clinit>(class_2539.java:217) ~[server-intermediary.jar:?]
                at net.fabricmc.fabric.impl.networking.server.ServerNetworkingImpl.<clinit>(ServerNetworkingImpl.java:41) ~[fabric-networking-api-v1-3.0.10+b1792f7da0-7978eacecef623d6.jar:?]
                at net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking.registerGlobalReceiver(ServerPlayNetworking.java:86) ~[fabric-networking-api-v1-3.0.10+b1792f7da0-7978eacecef623d6.jar:?]
                at net.kyori.adventure.platform.fabric.impl.ServerboundRegisteredArgumentTypesPacket.register(ServerboundRegisteredArgumentTypesPacket.java:47) ~[adventure-platform-fabric-5.10.0-144eb7082e02c5d6.jar:?]
                at net.kyori.adventure.platform.fabric.impl.AdventureCommon.setupCustomArgumentTypes(AdventureCommon.java:231) ~[adventure-platform-fabric-5.10.0-144eb7082e02c5d6.jar:?]
                at net.kyori.adventure.platform.fabric.impl.AdventureCommon.onInitialize(AdventureCommon.java:182) ~[adventure-platform-fabric-5.10.0-144eb7082e02c5d6.jar:?]
                ... 7 more
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    net/minecraft/class_2889.<init>(Lnet/minecraft/class_2540;)V @10: invokespecial
  Reason:
    Type uninitializedThis (current frame, stack[3]) is not assignable to 'net/minecraft/class_2889'
  Current Frame:
    bci: @10
    flags: { flagThisUninit }
    locals: { uninitializedThis, 'net/minecraft/class_2540' }
    stack: { uninitializedThis, integer, 'net/minecraft/class_2540', uninitializedThis, integer }
  Bytecode:
    0000000: 2a2b b600 332b 2a11 00ff b700 37b6 003b
    0000010: 2bb6 003e 2bb6 0033 b800 44b7 0046 b1

        at net.minecraft.class_2539.<clinit>(class_2539.java:217) ~[server-intermediary.jar:?]
        at net.fabricmc.fabric.impl.networking.server.ServerNetworkingImpl.<clinit>(ServerNetworkingImpl.java:41) ~[fabric-networking-api-v1-3.0.10+b1792f7da0-7978eacecef623d6.jar:?]
        at net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking.registerGlobalReceiver(ServerPlayNetworking.java:86) ~[fabric-networking-api-v1-3.0.10+b1792f7da0-7978eacecef623d6.jar:?]
        at net.kyori.adventure.platform.fabric.impl.ServerboundRegisteredArgumentTypesPacket.register(ServerboundRegisteredArgumentTypesPacket.java:47) ~[adventure-platform-fabric-5.10.0-144eb7082e02c5d6.jar:?]
        at net.kyori.adventure.platform.fabric.impl.AdventureCommon.setupCustomArgumentTypes(AdventureCommon.java:231) ~[adventure-platform-fabric-5.10.0-144eb7082e02c5d6.jar:?]
        at net.kyori.adventure.platform.fabric.impl.AdventureCommon.onInitialize(AdventureCommon.java:182) ~[adventure-platform-fabric-5.10.0-144eb7082e02c5d6.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:383) ~[fabric-loader-0.14.24.jar:?]
        ... 6 more
```
