### PR TITLE
Support for SnakeYaml 2.0+ (Velocity 3.5.0 and later)

### LINKED ISSUE #649: Velocity 3.5.0: Suddenly account linking no longer works & "Linking is not enabled on this server"
Hi everyone,

we're using floodgate 2.2.5-SNAPSHOT (b126-096c605) on our 1.21.11 network using Paper + Velocity + Geyser Standalone.

Account linking has always been working fine until recently - suddenly bedrock players who had previously linked their account always join using their bedrock account instead of their Java account, and when I try to use /linkaccount myself again, it says "Linking is not enabled on this server".

We're using floodgate both on the proxies, and on the backend servers, and the auth-type in geyser (standalone) is set to "floodgate".

Our floodgate config is the same on each proxy and each backend server: https://pastebin.com/gXMwArqG

~~There are no exceptions in the console and we haven't changed our floodgate configuration since forever.~~ (EDIT: See my reply, we've got an exception regarding the mysql extension) The mysql config is of course also the same on each server and we got floodgate-mysql-database.jar installed in each floodgate directory.

I am not sure whether this happened since we updated from 1.21.8 to 1.21.11, or since we updated to Velocity 3.5.0, or whether it specifically happened when we updated from an earlier 1.21.11 Paper to Paper 1.21.11 Build 111.

We're currently running these versions:

Paper version 1.21.11-111-main@302c47c (2026-02-07T22:59:49Z) (Implementing API version 1.21.11-R0.1-SNAPSHOT)
Geyser version 2.9.3-b1071 (git-master-946235f) (Java: 1.21.11, Bedrock: 1.21.111 - 26.0)
Velocity 3.5.0-SNAPSHOT (git-7e01491e-b574)
floodgate 2.2.5-SNAPSHOT (b126-096c605)

Anyone got any idea why this is happening / how to debug this? Any help would be appreciated! Thanks everyone & have a nice day.

### PR DESCRIPTION
**Pull request by mfnalex**
Fixes #649

Since SnakeYaml 2.0, the CustomClassLoaderConstructor requires a LoaderOptions object as second parameter. This PR simply catches the NoSuchMethodError and then tries again with the new Constructor through reflection.

Works fine for me on Velocity 3.5.0-SNAPSHOT (git-e0db2566-b577)

### CODE REVIEW

**Comment by WouterGritter** [comment]
I would really like to see this merged, as floodgate is currently still broken on the latest Velocity(-CTD).

**Comment by Tim203** [comment]
Thanks for the reminder. I think that this PR looks good.
This will at least make Floodgate work again. I really don't have time to make the changes needed for that other PR that also makes local linking work for those new Velocity versions.

**Review by Tim203 — APPROVED** [review]

**Comment by mfnalex** [comment]
Thanks for merging. Local linking does work fine for us using this version, btw (using MySQL backend, not SQLite though as also mentioned in the other PR)
